version: 2


models:
  - name: order_header
    columns:
      - name: sales_document
        tests:
          - not_null
          - unique
  - name: order_item_detail
    columns:
      - name: sales_document_item
        tests:
          - not_null
          - unique